# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcsi.proto\x12\x03\x63si\"d\n\nNexmonData\x12\x15\n\x03\x63si\x18\x01 \x03(\x0b\x32\x08.csi.CSI\x12\x0c\n\x04rssi\x18\x02 \x01(\x05\x12\x0c\n\x04\x66\x63tl\x18\x03 \x01(\r\x12\x12\n\nsource_mac\x18\x04 \x01(\x04\x12\x0f\n\x07seq_num\x18\x05 \x01(\r\"&\n\x03\x43SI\x12\x0c\n\x04real\x18\x01 \x01(\x05\x12\x11\n\timaginary\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEXMONDATA._serialized_start=18
  _NEXMONDATA._serialized_end=118
  _CSI._serialized_start=120
  _CSI._serialized_end=158
# @@protoc_insertion_point(module_scope)
